Update README.md
af-joint-project/joint-project pull request #32
Opened 2023-05-31 08:19 UTC by Ch84

2023-05-31 08:20 UTC, Ch84 commented
Lagt in tips på marknadsföring

2023-06-01 09:06 UTC, KhosroJadidiDeveloper requested changes
vänligen ta bort rad 55.

2023-06-01 09:13 UTC, Ch84 reviewed
tagit bort sista raden i readme #28

2023-06-06 12:47 UTC, KhosroJadidiDeveloper approved these changes
ser fint ut! tack 👍

2023-06-28 07:11 UTC, merged